"""ARIA Lite - the script that drives the animator parameters.

WHY ARIA OWNS THE SOURCE
------------------------
The animation pipeline builds a controller whose states are driven by
eight parameters, and a controller nobody sets is a character that
stands still. This is the other half: one MonoBehaviour that computes
those eight from movement and input, delivered into a project the same
way a clip or a prefab is.

Keeping the C# here rather than in the Unity project means the next
character gets the same script without anybody copying a file, and it
means the parameter names have exactly one definition -- the ones in
animation_parameters, repeated here and checked by a test.

WHY THE NEW INPUT SYSTEM
------------------------
Measured, not assumed: this project's ProjectSettings say

    activeInputHandler: 1

which is the new Input System ONLY. Legacy Input.GetAxis does not
work, so a script written against it would compile and then throw at
runtime -- the worst way to find out. It reads Keyboard and Mouse
directly rather than through an .inputactions asset, so it needs no
setup beyond the package already being installed.

WHY A CharacterController
-------------------------
It gives `isGrounded` and `velocity` for nothing, and those are two of
the eight parameters. A Rigidbody would work and would need the
grounded test written by hand, which is the part people get wrong.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence

from logger import get_logger

from backend.unity import animation_parameters as params
from backend.unity import unity_delivery as delivery

logger = get_logger(__name__)

__all__ = [
    "CLASS_NAME",
    "DEFAULT_SCRIPT_FOLDER",
    "SOURCE",
    "attach",
    "deliver",
    "script_path",
]

CLASS_NAME = "AriaCharacterController"
DEFAULT_SCRIPT_FOLDER = "Assets/ARIA/Scripts"

# The C# itself. No formatting is applied to it -- braces are left
# alone and the class name is fixed -- so what is read here is exactly
# what lands in the project.
SOURCE = '''// Generated by ARIA Lite. Drives the parameters on the AnimatorController
// that the animation pipeline builds.
//
// PARAMETERS, and what each one means:
//
//   speed       Float   horizontal metres per second. Idle/Walk/Run
//                       switch on it, and the Jump and Fall blend
//                       trees choose their variant by it.
//   landForce   Float   0..1, how hard the last landing was. The Land
//                       blend tree runs from a soft landing at 0 to a
//                       flat impact at 1. NOT speed: a fast run into a
//                       gentle step down is not a hard landing.
//   grounded    Bool    on the floor. Fall is entered from AnyState
//                       when this is false, so it is a state of the
//                       world rather than an event.
//   crouch      Bool    held or toggled, your choice below.
//   attack      Trigger
//   jump        Trigger
//   dodgeLeft   Trigger
//   dodgeRight  Trigger
//
// This reads Keyboard and Mouse directly because the project is set to
// the new Input System (activeInputHandler: 1) and legacy Input does
// not work. Swap ReadInput for your own action asset when you have one
// -- nothing else here depends on how the values arrive.

using UnityEngine;
using UnityEngine.InputSystem;

[RequireComponent(typeof(CharacterController))]
[RequireComponent(typeof(Animator))]
public class AriaCharacterController : MonoBehaviour
{
    [Header("Movement")]
    [Tooltip("Metres per second when walking.")]
    public float walkSpeed = 1.5f;

    [Tooltip("Metres per second when running. Must exceed the Walk to "
             + "Run threshold on the controller, which is 2.")]
    public float runSpeed = 4.0f;

    [Tooltip("Metres per second while crouched.")]
    public float crouchSpeed = 0.9f;

    [Tooltip("How quickly the character turns to face its heading.")]
    public float turnSeconds = 0.1f;

    [Header("Jumping")]
    public float jumpHeight = 1.2f;
    public float gravity = -19.62f;

    [Tooltip("Downward speed treated as the hardest possible landing. "
             + "Impacts at or above this set landForce to 1.")]
    public float hardLandingSpeed = 12.0f;

    [Header("Input")]
    [Tooltip("Hold to crouch, or press to toggle.")]
    public bool crouchIsToggle = false;

    [Tooltip("Movement is relative to this transform when set, and to "
             + "the world axes when it is not.")]
    public Transform cameraTransform;

    // Hashes rather than strings: SetFloat(string) does the lookup
    // every call, and this runs every frame.
    static readonly int SpeedId = Animator.StringToHash("speed");
    static readonly int LandForceId = Animator.StringToHash("landForce");
    static readonly int GroundedId = Animator.StringToHash("grounded");
    static readonly int CrouchId = Animator.StringToHash("crouch");
    static readonly int AttackId = Animator.StringToHash("attack");
    static readonly int JumpId = Animator.StringToHash("jump");
    static readonly int DodgeLeftId = Animator.StringToHash("dodgeLeft");
    static readonly int DodgeRightId = Animator.StringToHash("dodgeRight");

    CharacterController _controller;
    Animator _animator;

    Vector2 _move;
    bool _running;
    bool _crouching;
    float _verticalSpeed;
    float _turnVelocity;

    // The speed the character was falling at on the frame before it
    // touched down. Reading it after landing is too late: the
    // controller has already zeroed the vertical speed.
    float _fallSpeedLastFrame;
    bool _wasGrounded = true;

    void Awake()
    {
        _controller = GetComponent<CharacterController>();
        _animator = GetComponent<Animator>();
    }

    void Update()
    {
        ReadInput();
        Move();
        DriveAnimator();
    }

    // Replace this method to use an action asset. Everything below it
    // works from _move, _running and _crouching.
    void ReadInput()
    {
        var keyboard = Keyboard.current;
        var mouse = Mouse.current;
        if (keyboard == null) { _move = Vector2.zero; return; }

        float x = 0f, y = 0f;
        if (keyboard.aKey.isPressed || keyboard.leftArrowKey.isPressed) x -= 1f;
        if (keyboard.dKey.isPressed || keyboard.rightArrowKey.isPressed) x += 1f;
        if (keyboard.sKey.isPressed || keyboard.downArrowKey.isPressed) y -= 1f;
        if (keyboard.wKey.isPressed || keyboard.upArrowKey.isPressed) y += 1f;
        _move = new Vector2(x, y);
        if (_move.sqrMagnitude > 1f) _move.Normalize();

        _running = keyboard.leftShiftKey.isPressed;

        if (crouchIsToggle)
        {
            if (keyboard.cKey.wasPressedThisFrame) _crouching = !_crouching;
        }
        else
        {
            _crouching = keyboard.cKey.isPressed
                         || keyboard.leftCtrlKey.isPressed;
        }

        if (keyboard.spaceKey.wasPressedThisFrame && _controller.isGrounded)
        {
            _animator.SetTrigger(JumpId);
            _verticalSpeed = Mathf.Sqrt(jumpHeight * -2f * gravity);
        }

        bool attacked = keyboard.jKey.wasPressedThisFrame
                        || (mouse != null && mouse.leftButton.wasPressedThisFrame);
        if (attacked) _animator.SetTrigger(AttackId);

        if (keyboard.qKey.wasPressedThisFrame) _animator.SetTrigger(DodgeLeftId);
        if (keyboard.eKey.wasPressedThisFrame) _animator.SetTrigger(DodgeRightId);
    }

    void Move()
    {
        Vector3 heading = new Vector3(_move.x, 0f, _move.y);
        if (cameraTransform != null && heading.sqrMagnitude > 0.0001f)
        {
            // Flattened: a camera looking down would otherwise walk the
            // character into the floor.
            Vector3 forward = cameraTransform.forward;
            Vector3 right = cameraTransform.right;
            forward.y = 0f; right.y = 0f;
            heading = (forward.normalized * _move.y
                       + right.normalized * _move.x);
        }

        float target = _crouching ? crouchSpeed
                                  : (_running ? runSpeed : walkSpeed);
        Vector3 planar = heading * target;

        if (heading.sqrMagnitude > 0.0001f)
        {
            float wanted = Mathf.Atan2(heading.x, heading.z) * Mathf.Rad2Deg;
            float angle = Mathf.SmoothDampAngle(
                transform.eulerAngles.y, wanted, ref _turnVelocity,
                Mathf.Max(0.0001f, turnSeconds));
            transform.rotation = Quaternion.Euler(0f, angle, 0f);
        }

        // Remembered BEFORE the move, because the move is what lands
        // the character and zeroes the fall.
        _fallSpeedLastFrame = -_verticalSpeed;

        if (_controller.isGrounded && _verticalSpeed < 0f)
        {
            // A small negative rather than zero: exactly zero makes
            // isGrounded flicker on slopes and steps.
            _verticalSpeed = -2f;
        }
        _verticalSpeed += gravity * Time.deltaTime;

        _controller.Move((planar + Vector3.up * _verticalSpeed)
                         * Time.deltaTime);
    }

    void DriveAnimator()
    {
        bool grounded = _controller.isGrounded;

        Vector3 planar = _controller.velocity;
        planar.y = 0f;
        _animator.SetFloat(SpeedId, planar.magnitude);
        _animator.SetBool(GroundedId, grounded);
        _animator.SetBool(CrouchId, _crouching);

        // Set on the frame of the landing only. Left at its last value
        // it would make the next gentle landing play a flat impact.
        if (grounded && !_wasGrounded)
        {
            float force = Mathf.Clamp01(
                _fallSpeedLastFrame / Mathf.Max(0.01f, hardLandingSpeed));
            _animator.SetFloat(LandForceId, force);
        }
        _wasGrounded = grounded;
    }
}
'''


def script_path(folder: str = DEFAULT_SCRIPT_FOLDER) -> str:
    clean = str(folder or DEFAULT_SCRIPT_FOLDER).replace(
        delivery.SLASH, "/").strip("/")
    if not clean.lower().startswith("assets"):
        clean = f"Assets/{clean}"
    return f"{clean}/{CLASS_NAME}.cs"


def parameters_used() -> List[str]:
    """Every animator parameter the script sets.

    Read out of the C# rather than listed twice. A parameter renamed in
    animation_parameters and not here is a controller the script drives
    with the wrong name, and nothing complains -- SetFloat on an unknown
    parameter is silent.
    """
    found: List[str] = []
    for line in SOURCE.splitlines():
        if "Animator.StringToHash(" not in line:
            continue
        piece = line.split("Animator.StringToHash(", 1)[1]
        if '"' in piece:
            name = piece.split('"')[1]
            if name and name not in found:
                found.append(name)
    return found


def deliver(folder: str = DEFAULT_SCRIPT_FOLDER, *,
            overwrite: bool = True) -> dict:
    """Write the script into the project and let Unity compile it."""
    root = delivery.unity_project_root()
    if root is None:
        return delivery._failure(
            "No Unity project is configured, so there is nowhere to put it.")

    relative = script_path(folder)
    target = root / relative
    if target.exists() and not overwrite:
        return {"success": True, "ran": False, "error": None,
                "path": relative, "written": False,
                "parameters": parameters_used()}

    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(SOURCE, encoding="utf-8")
    except OSError as error:
        return delivery._failure(f"Could not write {relative}: {error}")

    refreshed = delivery._run("eval", {
        "code": 'UnityEditor.AssetDatabase.Refresh('
                'UnityEditor.ImportAssetOptions.ForceUpdate); '
                'return "ok";',
        "timeout": 180000,
    })

    return {"success": True, "ran": True, "error": None,
            "path": relative, "written": True,
            "refreshed": bool(refreshed["success"]),
            "parameters": parameters_used()}


def attach(target: str) -> dict:
    """Put the script on an object, once Unity has compiled it.

    A compile that has not finished means the type does not exist yet,
    and add_component says so rather than silently doing nothing --
    which is why this reports the Editor's own words.
    """
    return delivery.ensure_component(target, CLASS_NAME)
