"""ARIA Lite - the script that drives the animator parameters.

WHY ARIA OWNS THE SOURCE
------------------------
The animation pipeline builds a controller whose states are driven by
eight parameters, and a controller nobody sets is a character that
stands still. This is the other half: one MonoBehaviour that computes
those eight from movement and input, delivered into a project the same
way a clip or a prefab is.

Keeping the C# here rather than in the Unity project means the next
character gets the same script without anybody copying a file, and it
means the parameter names have exactly one definition -- the ones in
animation_parameters, repeated here and checked by a test.

WHY THE NEW INPUT SYSTEM
------------------------
Measured, not assumed: this project's ProjectSettings say

    activeInputHandler: 1

which is the new Input System ONLY. Legacy Input.GetAxis does not
work, so a script written against it would compile and then throw at
runtime -- the worst way to find out. It reads Keyboard and Mouse
directly rather than through an .inputactions asset, so it needs no
setup beyond the package already being installed.

WHY A CharacterController
-------------------------
It gives `isGrounded` and `velocity` for nothing, and those are two of
the eight parameters. A Rigidbody would work and would need the
grounded test written by hand, which is the part people get wrong.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence

from logger import get_logger

from backend.unity import animation_parameters as params
from backend.unity import unity_delivery as delivery

logger = get_logger(__name__)

__all__ = [
    "CLASS_NAME",
    "DEFAULT_SCRIPT_FOLDER",
    "SOURCE",
    "attach",
    "compiled_fields",
    "declared_fields",
    "deliver",
    "script_path",
    "stop_root_motion",
    "verify_compiled",
]

CLASS_NAME = "AriaCharacterController"
DEFAULT_SCRIPT_FOLDER = "Assets/ARIA/Scripts"

# The C# itself. No formatting is applied to it -- braces are left
# alone and the class name is fixed -- so what is read here is exactly
# what lands in the project.
SOURCE = '''// Generated by ARIA Lite. Drives the parameters on the AnimatorController
// that the animation pipeline builds.
//
// PARAMETERS, and what each one means:
//
//   speed       Float   horizontal metres per second. Idle/Walk/Run
//                       switch on it, and the Jump and Fall blend
//                       trees choose their variant by it.
//   landForce   Float   0..1, how hard the last landing was. The Land
//                       blend tree runs from a soft landing at 0 to a
//                       flat impact at 1. NOT speed: a fast run into a
//                       gentle step down is not a hard landing.
//   grounded    Bool    on the floor. Fall is entered from AnyState
//                       when this is false, so it is a state of the
//                       world rather than an event.
//   crouch      Bool    held or toggled, your choice below.
//   attack      Trigger
//   jump        Trigger
//   dodgeLeft   Trigger
//   dodgeRight  Trigger
//
// This reads Keyboard and Mouse directly because the project is set to
// the new Input System (activeInputHandler: 1) and legacy Input does
// not work. Swap ReadInput for your own action asset when you have one
// -- nothing else here depends on how the values arrive.

using UnityEngine;
using UnityEngine.InputSystem;

[RequireComponent(typeof(CharacterController))]
[RequireComponent(typeof(Animator))]
public class AriaCharacterController : MonoBehaviour
{
    [Header("Movement")]
    [Tooltip("Metres per second when walking.")]
    public float walkSpeed = 1.5f;

    [Tooltip("Metres per second when running. Must exceed the Walk to "
             + "Run threshold on the controller, which is 2.")]
    public float runSpeed = 4.0f;

    [Tooltip("Metres per second while crouched.")]
    public float crouchSpeed = 0.9f;

    [Tooltip("How quickly the character turns to face its heading.")]
    public float turnSeconds = 0.1f;

    [Header("Jumping")]
    public float jumpHeight = 1.2f;
    public float gravity = -19.62f;

    [Tooltip("Downward speed treated as the hardest possible landing. "
             + "Impacts at or above this set landForce to 1.")]
    public float hardLandingSpeed = 20.0f;

    [Tooltip("Downward speed below which a landing is soft. A 1.2m jump "
             + "lands at about 6.9 m/s, and that should not be a roll.")]
    public float softLandingSpeed = 8.0f;

    [Tooltip("How long after leaving the ground the character may still "
             + "jump, and how long before `grounded` is reported false. "
             + "CharacterController.isGrounded flickers, and without "
             + "this the jump misses presses and the fall triggers on "
             + "level floor.")]
    public float groundedGrace = 0.15f;

    // Declared OUTSIDE the [Header] that follows: Header is valid on a
    // field or property and not on a type, and putting it here was a
    // CS0592 that left Unity running the previously compiled version
    // while every file on disk looked correct.
    public enum Steering
    {
        // A and D turn the character; W and S move along its facing.
        TurnAndWalk,
        // A and D walk west and east. Needs a camera to make sense of,
        // and without one the character snaps to compass directions.
        DirectionIsAbsolute,
    }

    [Header("Input")]
    [Tooltip("TurnAndWalk: A/D turn, W/S move along the facing. "
             + "DirectionIsAbsolute: each key walks a world direction, "
             + "which needs a camera to read naturally.")]
    public Steering steering = Steering.TurnAndWalk;

    [Tooltip("Degrees per second when turning.")]
    public float turnSpeed = 180f;

    [Tooltip("Hold to crouch, or press to toggle.")]
    public bool crouchIsToggle = false;

    [Tooltip("Only used by DirectionIsAbsolute. Movement is relative to "
             + "this transform when set, and to the world axes when it "
             + "is not.")]
    public Transform cameraTransform;

    // Hashes rather than strings: SetFloat(string) does the lookup
    // every call, and this runs every frame.
    static readonly int SpeedId = Animator.StringToHash("speed");
    static readonly int LandForceId = Animator.StringToHash("landForce");
    static readonly int GroundedId = Animator.StringToHash("grounded");
    static readonly int CrouchId = Animator.StringToHash("crouch");
    static readonly int AttackId = Animator.StringToHash("attack");
    static readonly int JumpId = Animator.StringToHash("jump");
    static readonly int DodgeLeftId = Animator.StringToHash("dodgeLeft");
    static readonly int DodgeRightId = Animator.StringToHash("dodgeRight");

    CharacterController _controller;
    Animator _animator;

    Vector2 _move;
    bool _running;
    bool _crouching;
    float _verticalSpeed;
    float _turnVelocity;

    // The speed the character was falling at on the frame before it
    // touched down. Reading it after landing is too late: the
    // controller has already zeroed the vertical speed.
    float _fallSpeedLastFrame;
    bool _wasGrounded = true;

    // CharacterController.isGrounded is false on scattered frames while
    // standing on level ground. Reported as "jumping standing still
    // doesn't work all the time" -- the press landed on one of those
    // frames -- and it also fires the Fall transition on a flat floor.
    // So grounded is remembered for a moment rather than read raw.
    float _lastGroundedAt = -999f;
    bool Grounded
    {
        get { return Time.time - _lastGroundedAt <= groundedGrace; }
    }

    void Awake()
    {
        _controller = GetComponent<CharacterController>();
        _animator = GetComponent<Animator>();
    }

    void Update()
    {
        ReadInput();
        Move();
        DriveAnimator();
    }

    // Replace this method to use an action asset. Everything below it
    // works from _move, _running and _crouching.
    void ReadInput()
    {
        var keyboard = Keyboard.current;
        var mouse = Mouse.current;
        if (keyboard == null) { _move = Vector2.zero; return; }

        float x = 0f, y = 0f;
        if (keyboard.aKey.isPressed || keyboard.leftArrowKey.isPressed) x -= 1f;
        if (keyboard.dKey.isPressed || keyboard.rightArrowKey.isPressed) x += 1f;
        if (keyboard.sKey.isPressed || keyboard.downArrowKey.isPressed) y -= 1f;
        if (keyboard.wKey.isPressed || keyboard.upArrowKey.isPressed) y += 1f;
        _move = new Vector2(x, y);
        if (_move.sqrMagnitude > 1f) _move.Normalize();

        _running = keyboard.leftShiftKey.isPressed;

        if (crouchIsToggle)
        {
            if (keyboard.cKey.wasPressedThisFrame) _crouching = !_crouching;
        }
        else
        {
            _crouching = keyboard.cKey.isPressed
                         || keyboard.leftCtrlKey.isPressed;
        }

        if (keyboard.spaceKey.wasPressedThisFrame && Grounded)
        {
            _animator.SetTrigger(JumpId);
            _verticalSpeed = Mathf.Sqrt(jumpHeight * -2f * gravity);
        }

        bool attacked = keyboard.jKey.wasPressedThisFrame
                        || (mouse != null && mouse.leftButton.wasPressedThisFrame);
        if (attacked) _animator.SetTrigger(AttackId);

        if (keyboard.qKey.wasPressedThisFrame) _animator.SetTrigger(DodgeLeftId);
        if (keyboard.eKey.wasPressedThisFrame) _animator.SetTrigger(DodgeRightId);
    }

    void Move()
    {
        Vector3 planar;

        if (steering == Steering.TurnAndWalk)
        {
            // A and D turn; W and S move along the facing. This is the
            // scheme that behaves sensibly with no camera: pressing A
            // then W walks the way the character is now looking,
            // rather than snapping him back to north.
            transform.Rotate(0f, _move.x * turnSpeed * Time.deltaTime, 0f);
            float pace = _crouching ? crouchSpeed
                                    : (_running ? runSpeed : walkSpeed);
            planar = transform.forward * (_move.y * pace);
        }
        else
        {
            Vector3 heading = new Vector3(_move.x, 0f, _move.y);
            if (cameraTransform != null && heading.sqrMagnitude > 0.0001f)
            {
                // Flattened: a camera looking down would otherwise walk
                // the character into the floor.
                Vector3 forward = cameraTransform.forward;
                Vector3 right = cameraTransform.right;
                forward.y = 0f; right.y = 0f;
                heading = (forward.normalized * _move.y
                           + right.normalized * _move.x);
            }

            float pace = _crouching ? crouchSpeed
                                    : (_running ? runSpeed : walkSpeed);
            planar = heading.normalized * (heading.magnitude > 0.0001f
                                           ? pace : 0f);

            if (heading.sqrMagnitude > 0.0001f)
            {
                float wanted = Mathf.Atan2(heading.x, heading.z) * Mathf.Rad2Deg;
                float angle = Mathf.SmoothDampAngle(
                    transform.eulerAngles.y, wanted, ref _turnVelocity,
                    Mathf.Max(0.0001f, turnSeconds));
                transform.rotation = Quaternion.Euler(0f, angle, 0f);
            }
        }

        // Remembered BEFORE the move, because the move is what lands
        // the character and zeroes the fall.
        _fallSpeedLastFrame = -_verticalSpeed;

        if (_controller.isGrounded && _verticalSpeed < 0f)
        {
            // A small negative rather than zero: exactly zero makes
            // isGrounded flicker on slopes and steps.
            _verticalSpeed = -2f;
        }
        _verticalSpeed += gravity * Time.deltaTime;

        _controller.Move((planar + Vector3.up * _verticalSpeed)
                         * Time.deltaTime);

        // Raw here, buffered everywhere else. Rising counts as
        // airborne immediately, or the grace would let a jump report
        // grounded for its first tenth of a second.
        if (_controller.isGrounded && _verticalSpeed <= 0f)
            _lastGroundedAt = Time.time;
    }

    void DriveAnimator()
    {
        bool grounded = Grounded;

        Vector3 planar = _controller.velocity;
        planar.y = 0f;
        _animator.SetFloat(SpeedId, planar.magnitude);
        _animator.SetBool(GroundedId, grounded);
        _animator.SetBool(CrouchId, _crouching);

        // Set on the frame of the landing only. Left at its last value
        // it would make the next gentle landing play a flat impact.
        if (grounded && !_wasGrounded)
        {
            // Measured against the roll it was producing: a 1.2m jump
            // lands at about 6.9 m/s, and a straight divide by 12 made
            // that 0.57 -- which is the "Falling To Roll" child at 0.6.
            // A routine jump should be a landing, so everything below
            // softLandingSpeed is one, and the scale runs from there.
            float span = Mathf.Max(0.01f, hardLandingSpeed - softLandingSpeed);
            float force = Mathf.Clamp01(
                (_fallSpeedLastFrame - softLandingSpeed) / span);
            _animator.SetFloat(LandForceId, force);
        }
        _wasGrounded = grounded;
    }
}
'''


def script_path(folder: str = DEFAULT_SCRIPT_FOLDER) -> str:
    clean = str(folder or DEFAULT_SCRIPT_FOLDER).replace(
        delivery.SLASH, "/").strip("/")
    if not clean.lower().startswith("assets"):
        clean = f"Assets/{clean}"
    return f"{clean}/{CLASS_NAME}.cs"


def parameters_used() -> List[str]:
    """Every animator parameter the script sets.

    Read out of the C# rather than listed twice. A parameter renamed in
    animation_parameters and not here is a controller the script drives
    with the wrong name, and nothing complains -- SetFloat on an unknown
    parameter is silent.
    """
    found: List[str] = []
    for line in SOURCE.splitlines():
        if "Animator.StringToHash(" not in line:
            continue
        piece = line.split("Animator.StringToHash(", 1)[1]
        if '"' in piece:
            name = piece.split('"')[1]
            if name and name not in found:
                found.append(name)
    return found


def deliver(folder: str = DEFAULT_SCRIPT_FOLDER, *,
            overwrite: bool = True,
            compile_attempts: int = 6) -> dict:
    """Write the script into the project and let Unity compile it."""
    root = delivery.unity_project_root()
    if root is None:
        return delivery._failure(
            "No Unity project is configured, so there is nowhere to put it.")

    relative = script_path(folder)
    target = root / relative
    if target.exists() and not overwrite:
        return {"success": True, "ran": False, "error": None,
                "path": relative, "written": False,
                "parameters": parameters_used()}

    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(SOURCE, encoding="utf-8")
    except OSError as error:
        return delivery._failure(f"Could not write {relative}: {error}")

    delivery._run("eval", {
        "code": 'UnityEditor.AssetDatabase.Refresh('
                'UnityEditor.ImportAssetOptions.ForceUpdate); '
                'UnityEditor.Compilation.CompilationPipeline'
                '.RequestScriptCompilation(); return "ok";',
        "timeout": 180000,
    })

    # Unity compiles asynchronously, so the first look can legitimately
    # find the old assembly. Give it a few.
    report = {"checked": False, "compiled": False, "missing": [],
              "reason": "not checked"}
    for _ in range(int(compile_attempts)):
        report = verify_compiled()
        if report["compiled"]:
            break

    if report["compiled"]:
        problem = None
    elif not report["checked"]:
        problem = ("the file was written but whether Unity compiled it "
                   f"could not be checked: {report.get('reason')}")
    elif report["missing"]:
        problem = ("Unity is still running an older build of this script -- "
                   "it has no " + ", ".join(report["missing"][:4])
                   + ". Check the Console for a compile error.")
    else:
        problem = ("Unity has not compiled this script: "
                   + (report.get("reason") or "the type is not loaded"))

    return {"success": problem is None, "ran": True, "error": problem,
            "path": relative, "written": True,
            "checked": report["checked"], "compiled": report["compiled"],
            "missing": report["missing"],
            "parameters": parameters_used()}


# Unity keeps running the PREVIOUSLY compiled assembly when a script
# fails to compile. Nothing throws, the file on disk is correct, and
# the component in the scene is the old type -- which is exactly what
# happened here: a [Header] on an enum was a CS0592, deliver() reported
# success, and the new fields simply were not there.
# Whether the assembly Unity is RUNNING matches the source on disk.
#
# The Editor log was the first attempt and it is the wrong instrument:
# it accumulates, so errors from a compile three edits ago read as
# errors now. This asks the loaded type which public fields it has and
# compares them to the ones the source declares. A stale assembly is
# missing whatever the last edit added, which is exactly the symptom --
# the file on disk was correct, the component in the scene was the old
# type, and nothing anywhere said so.
_FIELDS = """
System.Type found = null;
foreach (var asm in System.AppDomain.CurrentDomain.GetAssemblies())
{
    var t = asm.GetType("CLASS_NAME");
    if (t != null) { found = t; break; }
}
if (found == null) return "NO_TYPE";
var sb = new System.Text.StringBuilder();
foreach (var f in found.GetFields(System.Reflection.BindingFlags.Public
                                  | System.Reflection.BindingFlags.Instance))
    sb.Append(f.Name).Append(",");
return sb.ToString();
"""


def declared_fields() -> List[str]:
    """The public instance fields the C# source declares."""
    found: List[str] = []
    for line in SOURCE.splitlines():
        text = line.strip()
        if not text.startswith("public ") or "(" in text or "{" in text:
            continue
        if text.startswith(("public enum", "public class", "public struct")):
            continue
        if "=" not in text and not text.endswith(";"):
            continue
        name = text.split("=")[0].strip().rstrip(";").split()[-1]
        if name and name not in found:
            found.append(name)
    return found


def compiled_fields(class_name: str = CLASS_NAME) -> dict:
    """What the loaded assembly's version of the class actually has."""
    outcome = delivery._run("eval", {
        "code": _FIELDS.replace("CLASS_NAME", class_name),
        "timeout": 120000,
    })
    if not outcome["success"]:
        return {"checked": False, "fields": [],
                "reason": outcome["error"] or "the type could not be read"}

    said = str(((outcome["data"] or {}) or {}).get("result") or "")
    if said == "NO_TYPE":
        return {"checked": True, "fields": [],
                "reason": f"{class_name} is not in any loaded assembly"}
    return {"checked": True,
            "fields": [n for n in said.split(",") if n], "reason": ""}


def verify_compiled(class_name: str = CLASS_NAME) -> dict:
    """Is Unity running THIS source, or a previous one?

    Returns checked, compiled, missing. `missing` is the public fields
    the source declares that the loaded type does not have, which is
    what a stale assembly looks like from the outside.
    """
    report = compiled_fields(class_name)
    if not report["checked"]:
        return {"checked": False, "compiled": False, "missing": [],
                "reason": report.get("reason", "")}

    have = set(report["fields"])
    missing = [name for name in declared_fields() if name not in have]
    return {"checked": True, "compiled": not missing and bool(have),
            "missing": missing, "reason": report.get("reason", "")}


# Root motion moves the character BY THE CLIP. With a
# CharacterController also moving him, the two fight: measured on this
# character as a jump that lands, falls into the air, lands again in
# mid-air and then drops. Mixamo's clips carry real vertical root
# motion and import with keepOriginalPositionY true, so this is not
# optional -- it is the difference between the script driving the
# character and the animation driving him.
_NO_ROOT_MOTION = """
var go = UnityEngine.GameObject.Find("NAME");
if (go == null) return "NO_OBJECT";
var an = go.GetComponent<UnityEngine.Animator>();
if (an == null) return "NO_ANIMATOR";
var was = an.applyRootMotion;
an.applyRootMotion = false;
UnityEditor.EditorUtility.SetDirty(go);

// AND THE PREFAB HE CAME FROM. Fixing only the instance in the scene
// is undone the next time the character is placed, which is the same
// bug arriving a second time and looking new.
var source = UnityEditor.PrefabUtility.GetCorrespondingObjectFromSource(go);
var asset = source != null ? source : null;
var prefabWas = "none";
if (asset != null)
{
    var pa = asset.GetComponent<UnityEngine.Animator>();
    if (pa != null)
    {
        prefabWas = pa.applyRootMotion.ToString();
        pa.applyRootMotion = false;
        UnityEditor.EditorUtility.SetDirty(asset);
        UnityEditor.AssetDatabase.SaveAssets();
    }
}
return "was=" + was + " now=" + an.applyRootMotion + " prefabWas=" + prefabWas;
"""


def stop_root_motion(target: str) -> dict:
    """Turn root motion off, because the CharacterController moves him.

    Both on the object in the scene AND on the prefab behind it: root
    motion moves the character by the clip, and with a
    CharacterController also moving him the two fight. Measured on this
    character as a jump that lands, falls into the air, lands again in
    mid-air and then drops.

    Returns success, whether it had been on, and whether the prefab
    needed the same fix.
    """
    outcome = delivery._run("eval", {
        "code": _NO_ROOT_MOTION.replace(
            "NAME", str(target or "").replace('"', "")),
        "timeout": 60000,
    })
    if not outcome["success"]:
        return {"success": False, "ran": True, "error": outcome["error"]}

    said = str(((outcome["data"] or {}) or {}).get("result") or "")
    if said in ("NO_OBJECT", "NO_ANIMATOR") or "now=" not in said:
        return {"success": False, "ran": True,
                "error": f"could not reach the Animator on {target}: "
                         f"{said or 'no answer'}"}

    return {"success": "now=False" in said, "ran": True, "error": None,
            "was_on": "was=True" in said,
            "prefab_was_on": "prefabWas=True" in said}


def attach(target: str) -> dict:
    """Put the script on an object, once Unity has compiled it.

    A compile that has not finished means the type does not exist yet,
    and add_component says so rather than silently doing nothing --
    which is why this reports the Editor's own words.
    """
    added = delivery.ensure_component(target, CLASS_NAME)
    if not added["success"]:
        return added

    # Not a separate step a caller can forget: attaching this script
    # IS the statement that physics drives the character.
    motion = stop_root_motion(target)
    added["root_motion_off"] = motion["success"]
    if not motion["success"]:
        added["warning"] = (
            "the script is attached but root motion could not be turned "
            f"off: {motion['error']}. The clips will fight the "
            "CharacterController for control of the character.")
    return added
