# backend/core/docs_generator.py

"""
Backend documentation generator — Phase 2, item 10.

Introspects the actual Phase 2 modules (docstrings, function signatures,
class members) and writes Markdown to /docs/backend/*.md. Deliberately
reads real `__doc__`/`inspect` data rather than hand-duplicating
descriptions here — if a module's docstring goes stale, so does its
generated doc, which is the honest failure mode (visible next time
someone reads it) rather than two independent descriptions silently
drifting apart.
"""

from __future__ import annotations

import inspect
from pathlib import Path
from typing import Any, List

from logger import get_logger

logger = get_logger(__name__)

DOCS_DIR = Path(__file__).resolve().parent.parent.parent / "docs" / "backend"


def _clean_doc(obj: Any) -> str:
    doc = inspect.getdoc(obj)
    return doc.strip() if doc else "_No docstring provided._"


def _public_members(module: Any, kind: str) -> List[tuple]:
    """kind: 'function' or 'class'."""
    predicate = inspect.isfunction if kind == "function" else inspect.isclass
    members = inspect.getmembers(module, predicate)
    return [
        (name, obj) for name, obj in members
        if not name.startswith("_") and getattr(obj, "__module__", None) == module.__name__
    ]


def _render_function_signature(name: str, fn: Any) -> str:
    try:
        sig = inspect.signature(fn)
        return f"`{name}{sig}`"
    except (ValueError, TypeError):
        return f"`{name}(...)`"


def _render_module_doc(title: str, module: Any) -> str:
    lines = [f"# {title}", "", _clean_doc(module), ""]

    classes = _public_members(module, "class")
    if classes:
        lines.append("## Classes")
        lines.append("")
        for name, cls in sorted(classes):
            lines.append(f"### `{name}`")
            lines.append("")
            lines.append(_clean_doc(cls))
            lines.append("")
            methods = [
                (mname, m) for mname, m in inspect.getmembers(cls, inspect.isfunction)
                if not mname.startswith("_") or mname == "__init__"
            ]
            for mname, method in sorted(methods):
                lines.append(f"- {_render_function_signature(mname, method)}")
                doc = _clean_doc(method)
                if doc != "_No docstring provided._":
                    first_line = doc.splitlines()[0]
                    lines.append(f"  {first_line}")
            lines.append("")

    functions = _public_members(module, "function")
    if functions:
        lines.append("## Functions")
        lines.append("")
        for name, fn in sorted(functions):
            lines.append(f"### {_render_function_signature(name, fn)}")
            lines.append("")
            lines.append(_clean_doc(fn))
            lines.append("")

    return "\n".join(lines)


# Every Phase 1 + Phase 2 subsystem this generator documents, and the
# output filename each writes to under /docs/backend/.
_DOC_TARGETS = [
    ("provider-api.md", "Provider API", "backend.core.provider_interface"),
    ("tool-registry.md", "Tool Registry", "backend.core.tool_registry"),
    ("sandbox.md", "Execution Sandbox", "backend.core.sandbox"),
    ("plugin-system.md", "Plugin System", "backend.core.plugin_registry"),
    ("execution-pipeline.md", "Unified Execution Pipeline", "backend.core.execution_pipeline"),
    ("streaming-engine-v2.md", "Streaming Engine v2", "backend.core.streaming_engine_v2"),
    ("cache-manager.md", "Cache Manager", "backend.core.cache_manager"),
    ("multi-tier-cache.md", "Multi-Tier Cache", "backend.core.multi_tier_cache"),
    ("errors.md", "Unified Error System", "backend.core.errors"),
    ("metrics.md", "Metrics & Telemetry", "backend.core.metrics"),
    ("model-info.md", "ModelInfo (Phase 1)", "backend.core.model_info"),
    ("hardware-snapshot-cache.md", "Hardware Snapshot Cache (Phase 1)", "backend.core.hardware_snapshot_cache"),
    ("diagnostics.md", "Diagnostics (REST + IPC)", "backend.rest.router"),
]


def generate_all(output_dir: Path = DOCS_DIR) -> List[str]:
    """Writes one .md per _DOC_TARGETS entry. Returns the list of files written."""
    import importlib

    output_dir.mkdir(parents=True, exist_ok=True)
    written = []

    for filename, title, module_path in _DOC_TARGETS:
        try:
            module = importlib.import_module(module_path)
        except Exception as e:
            logger.warning(f"docs_generator: failed to import {module_path}: {e}")
            continue

        content = _render_module_doc(title, module)
        out_path = output_dir / filename
        out_path.write_text(content, encoding="utf-8")
        written.append(str(out_path))
        logger.debug(f"docs_generator: wrote {out_path}")

    index_lines = ["# ARIA Lite Backend Documentation", "", "Auto-generated by `backend.core.docs_generator`. Do not hand-edit — regenerate instead.", ""]
    for filename, title, _ in _DOC_TARGETS:
        if (output_dir / filename).exists():
            index_lines.append(f"- [{title}]({filename})")
    index_path = output_dir / "README.md"
    index_path.write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    written.append(str(index_path))

    logger.info(f"docs_generator.generate_all() → wrote {len(written)} file(s) to {output_dir}")
    return written


if __name__ == "__main__":
    for path in generate_all():
        print(path)
