"""ARIA Lite - taking generated motion out of Blender as plain numbers.

WHY THE CURVES LEAVE AS JSON RATHER THAN AS AN FBX
--------------------------------------------------
Because the FBX route does not work, and that was measured rather than
assumed. The curves transfer onto the rig in Blender -- 315 of 315,
with the rig demonstrably moving -- the FBX exports, and Blender reads
50 actions and 230 moving curves back out of that same file. Unity
then answers

    importAnimation=True  animationType=Human  takes=0

No take, so no clip. Explicit bake flags and an NLA strip made no
difference. So the numbers come out as JSON and go into a .anim asset
directly, which is what curve_writer does.

WHAT COMES BACK, AND WHAT IS DROPPED
------------------------------------
Rotations only, per bone, as whole quaternions. Two things are left
behind on purpose:

  ROOT TRANSLATION. The animation's node positions are in the source
  model's scale, and the cleaned model in Unity has been scaled to
  1.8m with its transforms applied. Writing them raw threw the
  character metres across the scene -- feet at 7.7m for a 1.8m
  character. `mode: rot_only` puts the motion in the rotations anyway:
  measured, 128 of 180 rotation curves move and only 3 of 135 location
  curves do.

  ANY AXIS CONVERSION. Unity's importer carries the whole Z-up to Y-up
  rotation on the armature root and leaves every bone at identity, so
  a bone-local quaternion transfers unchanged. Verified against a live
  Editor: at t=0.25 Unity read back x=-0.2414 where the source frame
  holds -0.2272, the same rotation.

BLENDER 5 CHANGED WHERE FCURVES LIVE
------------------------------------
Actions are slotted now: `action.fcurves` is gone and the curves sit
under layers -> strips -> channelbags, one channelbag per slot. The
reader here handles both, because the version that ships is not this
module's business.
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional

from logger import get_logger

from backend.blender import blender_actions as actions
from backend.core import cli_runner

logger = get_logger(__name__)

__all__ = [
    "DEFAULT_FRAME_RATE",
    "SCRIPT",
    "export_curves",
    "read_dump",
]

# Ludo's motion comes back sampled at 30 keys over ~58 frames. The rate
# is what turns a frame number into the seconds Unity times keys in,
# and it is a parameter because nothing guarantees it stays 30.
DEFAULT_FRAME_RATE = 30.0

# The Blender side. Kept as one string rather than a file on disk so
# there is exactly one copy of it and it travels with the module.
SCRIPT = '''"""Generated by ARIA Lite. Do not edit -- it is rewritten per run."""
import bpy
import json
import sys

argv = sys.argv[sys.argv.index("--") + 1:]
animation_path, out_path = argv[0], argv[1]
rigged_path = argv[2] if len(argv) > 2 else ""

bpy.ops.wm.read_factory_settings(use_empty=True)


def _import(path):
    kind = path.rsplit(".", 1)[-1].lower() if "." in path else ""
    if kind in ("glb", "gltf"):
        bpy.ops.import_scene.gltf(filepath=path)
    elif kind == "fbx":
        bpy.ops.import_scene.fbx(filepath=path)
    else:
        raise RuntimeError("I do not know how to import %r" % path)


def _slots(action):
    """{slot identifier: [fcurve]}, on Blender 4 or 5.

    Blender 5 moved fcurves under layers -> strips -> channelbags and
    removed action.fcurves entirely.
    """
    found = {}
    for layer in getattr(action, "layers", []):
        for strip in getattr(layer, "strips", []):
            for bag in getattr(strip, "channelbags", []):
                name = getattr(getattr(bag, "slot", None), "identifier", "") or ""
                found.setdefault(name, []).extend(bag.fcurves)
    if not found and hasattr(action, "fcurves"):
        found[""] = list(action.fcurves)
    return found


# The rig is optional: it is imported only so bones that the animation
# names but the skeleton does not have can be reported rather than
# written and silently ignored later.
known_bones = []
if rigged_path:
    _import(rigged_path)
    for obj in bpy.data.objects:
        if obj.type == "ARMATURE":
            known_bones = sorted(b.name for b in obj.data.bones)

before = set(bpy.data.actions)
_import(animation_path)
fresh = [a for a in bpy.data.actions if a not in before]
if not fresh:
    raise RuntimeError("that animation file contains no action")
action = fresh[0]

bones = {}
for identifier, curves in _slots(action).items():
    bone = identifier[2:] if identifier.startswith("OB") else identifier
    if not bone:
        continue
    entry = bones.setdefault(bone, {})
    for curve in curves:
        channel = curve.data_path.rsplit(".", 1)[-1]
        entry.setdefault(channel, {})[curve.array_index] = [
            [round(k.co[0], 4), round(k.co[1], 6)] for k in curve.keyframe_points
        ]

# Rotations only, assembled into whole quaternions in Blender's w,x,y,z
# order. The consumer reorders; this side does not guess.
clips = []
dropped = []
for bone in sorted(bones):
    channels = bones[bone]
    if "location" in channels:
        dropped.append(bone)
    quaternion = channels.get("rotation_quaternion")
    if not quaternion or len(quaternion) < 4:
        continue

    frames = [key[0] for key in quaternion[0]]
    keys = []
    for index, frame in enumerate(frames):
        keys.append({
            "frame": frame,
            "wxyz": [quaternion[component][index][1] for component in range(4)],
        })
    clips.append({"bone": bone, "property": "rotation", "keys": keys})

moving = 0
for entry in clips:
    for component in range(4):
        values = [key["wxyz"][component] for key in entry["keys"]]
        if len(values) > 1 and (max(values) - min(values)) > 1e-4:
            moving += 1

payload = {
    "action": action.name,
    "bones": clips,
    "bone_count": len(clips),
    "moving_curves": moving,
    "dropped_translation_for": dropped,
    "rig_bones": known_bones,
    "unknown_to_rig": sorted(set(e["bone"] for e in clips) - set(known_bones))
                      if known_bones else [],
}

with open(out_path, "w", encoding="utf-8") as handle:
    json.dump(payload, handle, indent=1)

print("ARIA_CURVES bones=%d moving=%d dropped=%d" % (
    len(clips), moving, len(dropped)))
'''


def read_dump(path: str) -> Dict[str, Any]:
    try:
        with open(path, encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, ValueError):
        logger.exception("could not read the curve dump at %s", path)
        return {}


def export_curves(animation_path: str, out_json: str, *,
                  rigged_path: str = "",
                  timeout: Optional[int] = None,
                  on_output=None) -> dict:
    """Pull the rotation curves out of an animation GLB.

    `rigged_path` is optional and only used to report bones the
    animation names that the skeleton does not have -- a mismatch that
    otherwise shows up as a character animating three quarters of
    itself.

    Returns success, ran, error, dump, bones, moving_curves and the
    path the JSON was written to.
    """
    source = str(animation_path or "").strip()
    if not source:
        return {"success": False, "ran": False, "dump": {},
                "error": "I need an animation file to read.", "output": ""}
    if not Path(source).is_file():
        return {"success": False, "ran": False, "dump": {},
                "error": f"There is no file at {source}.", "output": ""}

    destination = str(out_json or "").strip()
    if not destination:
        destination = str(Path(source).with_suffix(".curves.json"))

    try:
        executable = actions.blender_path()
    except actions.BlenderUnavailable as error:
        return {"success": False, "ran": False, "dump": {},
                "error": str(error), "output": ""}

    handle, script_path = tempfile.mkstemp(prefix="aria-curves-", suffix=".py")
    with os.fdopen(handle, "w", encoding="utf-8") as file:
        file.write(SCRIPT)

    arguments = ["--background", "--factory-startup",
                 "--python", script_path, "--python-exit-code", "1",
                 "--", source, destination]
    if rigged_path:
        arguments.append(str(rigged_path))

    try:
        outcome = cli_runner.run(
            executable, arguments, on_output=on_output,
            timeout=int(timeout or actions.DEFAULT_TIMEOUT_SECONDS),
            label="blender")
    finally:
        Path(script_path).unlink(missing_ok=True)

    if not outcome.get("success"):
        return {"success": False, "ran": True, "dump": {},
                "error": outcome.get("error") or "Blender failed",
                "output": outcome.get("output") or ""}

    dump = read_dump(destination)
    if not dump.get("bones"):
        return {"success": False, "ran": True, "dump": dump,
                "error": "Blender finished but wrote no curves.",
                "output": outcome.get("output") or ""}

    return {
        "success": True, "ran": True, "error": None,
        "dump": dump,
        "json_path": destination,
        "bones": dump.get("bone_count", 0),
        "moving_curves": dump.get("moving_curves", 0),
        "dropped_translation_for": dump.get("dropped_translation_for") or [],
        "unknown_to_rig": dump.get("unknown_to_rig") or [],
        "output": outcome.get("output") or "",
    }
