# backend/bridge/api.py
from __future__ import annotations
from typing import Any, Dict, List
from fastapi import APIRouter, Body
from pydantic import BaseModel

from .state_manager import bridge_state
from .command_router import bridge_router

bridge_api = APIRouter(prefix="/bridge", tags=["ARIA–Copilot Bridge"])


# ============================================================
# BRIDGE COMMAND MODEL
# ============================================================
class BridgeCommand(BaseModel):
    session_id: str = "default"
    type: str
    message: str | None = None
    logs: Any | None = None
    context: str | None = None
    history: List[Dict[str, Any]] | None = None
    requirements: str | None = None
    metadata: Dict[str, Any] | None = None


# ============================================================
# MAIN BRIDGE COMMAND ENDPOINT
# ============================================================
@bridge_api.post("/command")
async def bridge_command(command: BridgeCommand = Body(...)) -> Dict[str, Any]:
    """
    Main ARIA–Copilot bridge entrypoint.
    Copilot sends structured commands here.
    ARIA processes them and returns unified structured replies.
    """

    payload = command.model_dump()

    try:
        result = bridge_router.handle_command(payload)

        # Normalize result structure
        if not isinstance(result, dict):
            return {
                "status": "error",
                "operation": "bridge_command",
                "detail": "Bridge router returned non-dict result"
            }

        result.setdefault("status", "ok")
        result.setdefault("operation", "bridge_command")
        result.setdefault("session_id", command.session_id)

        return result

    except Exception as e:
        return {
            "status": "error",
            "operation": "bridge_command",
            "session_id": command.session_id,
            "detail": str(e)
        }


# ============================================================
# BRIDGE STATUS ENDPOINT
# ============================================================
@bridge_api.get("/status")
async def bridge_status(session_id: str | None = None) -> Dict[str, Any]:
    """
    Returns current bridge/session status.
    Useful for ARIA, Copilot, or you to inspect:
      - active session
      - history length
      - last reply
      - last error
    """

    try:
        status = bridge_state.get_status(session_id)

        if not isinstance(status, dict):
            return {
                "status": "error",
                "operation": "bridge_status",
                "detail": "Bridge state returned non-dict result"
            }

        status.setdefault("status", "ok")
        status.setdefault("operation", "bridge_status")
        status.setdefault("session_id", session_id)

        return status

    except Exception as e:
        return {
            "status": "error",
            "operation": "bridge_status",
            "session_id": session_id,
            "detail": str(e)
        }


# ============================================================
# PACKET GENERATION ENDPOINT
# ============================================================
@bridge_api.get("/packet")
async def bridge_packet() -> Dict[str, Any]:
    """
    Returns a fully structured ARIA packet generated by the Copilot agent.
    """

    try:
        from .copilot_agent import copilot_agent
        packet = copilot_agent.build_packet()

        if not isinstance(packet, dict):
            return {
                "status": "error",
                "operation": "bridge_packet",
                "detail": "Copilot agent returned non-dict packet"
            }

        packet.setdefault("status", "ok")
        packet.setdefault("operation", "bridge_packet")

        return packet

    except Exception as e:
        return {
            "status": "error",
            "operation": "bridge_packet",
            "detail": str(e)
        }
