# backend/bridge/command_router.py
from __future__ import annotations
from typing import Any, Dict
from .state_manager import bridge_state
from backend.backend_connection import BackendConnection


class BridgeCommandRouter:
    """
    Unified ARIA–Copilot bridge command router.
    Handles:
      - chat commands
      - diagnostic commands
      - script generation requests
      - structured reply propagation
    """

    def __init__(self) -> None:
        self.chat_manager = None
        self.backend = BackendConnection()

    # ---------------------------------------------------------
    # ATTACH CHAT MANAGER
    # ---------------------------------------------------------
    def attach_chat_manager(self, chat_manager):
        """
        ARIA Lite attaches its REAL ChatManager here.
        Ensures:
          - shared sessions
          - shared history
          - shared backend status
        """
        self.chat_manager = chat_manager

    # ---------------------------------------------------------
    # MAIN COMMAND HANDLER
    # ---------------------------------------------------------
    def handle_command(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        session_id = payload.get("session_id") or "default"
        command_type = payload.get("type")
        metadata = payload.get("metadata") or {}

        # Ensure session exists
        bridge_state.create_session(session_id, name=metadata.get("name"))

        # Log command into history
        bridge_state.append_history(
            session_id=session_id,
            role="copilot_bridge",
            content=f"[COMMAND:{command_type}]",
            extra={"payload": payload},
        )

        # Dispatch
        if command_type == "chat":
            return self._handle_chat(session_id, payload)

        if command_type == "diagnose":
            return self._handle_diagnose(session_id, payload)

        if command_type == "script_request":
            return self._handle_script_request(session_id, payload)

        # Unknown command
        reply = {
            "status": "error",
            "operation": "handle_command",
            "session_id": session_id,
            "detail": f"Unknown command type: {command_type}",
        }
        bridge_state.set_last_error(session_id, reply["detail"])
        return reply

    # ---------------------------------------------------------
    # CHAT COMMAND
    # ---------------------------------------------------------
    def _handle_chat(self, session_id: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        if not self.chat_manager:
            return {
                "status": "error",
                "operation": "chat",
                "session_id": session_id,
                "detail": "ChatManager not attached"
            }

        message = payload.get("message") or ""

        try:
            reply_text = self.chat_manager.process_message(message)
        except Exception as e:
            reply_text = f"[ChatManager error] {e}"

        # Log user + ARIA messages
        bridge_state.append_history(session_id, role="user", content=message)
        bridge_state.append_history(session_id, role="aria", content=reply_text)

        reply = {
            "status": "ok",
            "operation": "chat_reply",
            "session_id": session_id,
            "reply": reply_text,
            "actions": [],
            "summary": None,
        }

        bridge_state.set_last_reply(session_id, reply)
        return reply

    # ---------------------------------------------------------
    # DIAGNOSTIC COMMAND
    # ---------------------------------------------------------
    def _handle_diagnose(self, session_id: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        logs = payload.get("logs")
        context = payload.get("context") or ""

        reply_text = f"Diagnostics received. Logs length: {len(str(logs))}. Context length: {len(context)}."

        reply = {
            "status": "ok",
            "operation": "diagnose_reply",
            "session_id": session_id,
            "reply": reply_text,
            "actions": [],
        }

        bridge_state.set_last_reply(session_id, reply)
        return reply

    # ---------------------------------------------------------
    # SCRIPT REQUEST COMMAND
    # ---------------------------------------------------------
    def _handle_script_request(self, session_id: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        context = payload.get("context") or ""
        requirements = payload.get("requirements") or ""

        # Simple script stub
        script = (
            "# Script generated by ARIA\n"
            f"# Context: {context}\n"
            f"# Requirements: {requirements}\n"
            "print('Hello from ARIA script')"
        )

        reply = {
            "status": "ok",
            "operation": "script_reply",
            "session_id": session_id,
            "reply": "Script generated.",
            "actions": [
                {
                    "type": "script",
                    "language": "python",
                    "content": script,
                }
            ],
            "summary": "Script generated successfully.",
        }

        bridge_state.set_last_reply(session_id, reply)
        return reply


# Singleton router
bridge_router = BridgeCommandRouter()
